# Generated by Django 2.2.7 on 2019-11-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-price'], 'verbose_name': '종목', 'verbose_name_plural': '주식 종목'},
        ),
        migrations.AlterModelOptions(
            name='predictedprice',
            options={'ordering': ['-now'], 'verbose_name': '종목 주가 예측', 'verbose_name_plural': '예측 주가'},
        ),
        migrations.AlterField(
            model_name='company',
            name='biz_type',
            field=models.CharField(max_length=20, verbose_name='업종'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=6, verbose_name='종목 코드'),
        ),
        migrations.AlterField(
            model_name='company',
            name='market_type',
            field=models.CharField(choices=[('KP', '코스피'), ('KD', '코스닥')], max_length=2, verbose_name='소속'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30, verbose_name='종목명'),
        ),
        migrations.AlterField(
            model_name='company',
            name='price',
            field=models.IntegerField(verbose_name='전일 종가'),
        ),
        migrations.AlterField(
            model_name='predictedprice',
            name='after_a_month',
            field=models.IntegerField(verbose_name='명월 예측 종가'),
        ),
        migrations.AlterField(
            model_name='predictedprice',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demo.Company', verbose_name='종목명'),
        ),
        migrations.AlterField(
            model_name='predictedprice',
            name='now',
            field=models.IntegerField(verbose_name='전일 종가'),
        ),
        migrations.AlterField(
            model_name='predictedprice',
            name='tomorrow',
            field=models.IntegerField(verbose_name='명일 예측 종가'),
        ),
    ]
