# Generated by Django 2.2.7 on 2019-11-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20191128_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('날짜', models.DateField(verbose_name='날짜')),
                ('price', models.IntegerField(verbose_name='시가')),
            ],
            options={
                'verbose_name': '주가',
                'verbose_name_plural': '날짜별 주가',
                'ordering': ['company'],
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': '종목', 'verbose_name_plural': '주식 종목'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='biz_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='price',
        ),
        migrations.DeleteModel(
            name='PredictedPrice',
        ),
        migrations.AddField(
            model_name='price',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Company', verbose_name='종목명'),
        ),
    ]
