# Generated by Django 2.2.7 on 2019-11-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20191128_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='날짜',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('company', 'date')},
        ),
    ]
