# Generated by Django 2.2.7 on 2019-11-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20191128_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['date'], 'verbose_name': '주가', 'verbose_name_plural': '날짜별 주가'},
        ),
        migrations.AlterField(
            model_name='price',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Company', verbose_name='종목'),
        ),
    ]
