# Generated by Django 2.2.7 on 2019-11-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20191128_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-date'], 'verbose_name': '주가', 'verbose_name_plural': '날짜별 주가'},
        ),
    ]
