# Generated by Django 2.2.7 on 2019-12-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20191202_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='market_type',
            field=models.CharField(choices=[('kospi', '코스피'), ('kosdaq', '코스닥')], max_length=2, verbose_name='소속'),
        ),
    ]
