# Generated by Django 2.2.7 on 2019-12-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20191211_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyitem',
            name='stock_code',
            field=models.CharField(max_length=6, null=True, verbose_name='종목코드'),
        ),
    ]
