# Generated by Django 2.2.7 on 2019-12-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_scrapyitem_stock_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='예측 날짜')),
                ('price', models.IntegerField(verbose_name='예측 주가')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Company', verbose_name='예측 종목')),
            ],
            options={
                'verbose_name': '예측 주가',
                'verbose_name_plural': '날짜별 예측 주가',
                'ordering': ['-date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
