# Generated by Django 2.2.7 on 2019-12-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_predictedprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapyitem',
            options={'ordering': ['-date'], 'verbose_name': '관련 뉴스', 'verbose_name_plural': '관련 뉴스'},
        ),
    ]
